#include "vk_xaku.h"
#ifdef XAKU_VULKAN

FN_XAKU_DEFERRED_RESOURCE_DISASSEMBLY(vulkan);

FN_XAKU_CREATE_BUFFER(vulkan);
FN_XAKU_CREATE_BUFFER_FROM_MEMORY(vulkan);
FN_XAKU_CREATE_TEXTURE(vulkan);
FN_XAKU_CREATE_TEXTURE_FROM_MEMORY(vulkan);
FN_XAKU_CREATE_TEXTURE_VIEW(vulkan);
FN_XAKU_CREATE_SAMPLER(vulkan);
FN_XAKU_CREATE_TLAS(vulkan);
FN_XAKU_CREATE_BLAS(vulkan);
FN_XAKU_CREATE_TLAS_FROM_BUFFER(vulkan);
FN_XAKU_CREATE_BLAS_FROM_BUFFER(vulkan);

FN_XAKU_GET_BUFFER_ASSEMBLY(vulkan);
FN_XAKU_GET_TEXTURE_ASSEMBLY(vulkan);
FN_XAKU_GET_TEXTURE_VIEW_ASSEMBLY(vulkan);
FN_XAKU_GET_SAMPLER_ASSEMBLY(vulkan);
FN_XAKU_GET_TLAS_BUILD_SIZES(vulkan);
FN_XAKU_GET_TLAS_ASSEMBLY(vulkan);
FN_XAKU_GET_BLAS_BUILD_SIZES(vulkan);
FN_XAKU_GET_BLAS_ASSEMBLY(vulkan);

FN_XAKU_DESTROY_BUFFER(vulkan);
FN_XAKU_DESTROY_TEXTURE(vulkan);
FN_XAKU_DESTROY_TEXTURE_VIEW(vulkan);
FN_XAKU_DESTROY_SAMPLER(vulkan);
FN_XAKU_DESTROY_TLAS(vulkan);
FN_XAKU_DESTROY_BLAS(vulkan);

#endif /* XAKU_VULKAN */
