#include "vk_xaku.h"
#ifdef XAKU_VULKAN

FN_XAKU_COMMAND_RECORDER_ASSEMBLY(vulkan);
FN_XAKU_COMMAND_RECORDER_DISASSEMBLY(vulkan);

FN_XAKU_CMD_COPY_BUFFER_TO_BUFFER(vulkan);
FN_XAKU_CMD_COPY_BUFFER_TO_TEXTURE(vulkan);
FN_XAKU_CMD_COPY_TEXTURE_TO_BUFFER(vulkan);
FN_XAKU_CMD_COPY_TEXTURE_TO_TEXTURE(vulkan);
FN_XAKU_CMD_BLIT_TEXTURE_TO_TEXTURE(vulkan);
FN_XAKU_CMD_CLEAR_BUFFER(vulkan);
FN_XAKU_CMD_CLEAR_TEXTURE(vulkan);
FN_XAKU_CMD_BUILD_ACCELERATION_STRUCTURES(vulkan);
FN_XAKU_CMD_DESTROY_BUFFER_DEFERRED(vulkan);
FN_XAKU_CMD_DESTROY_TEXTURE_DEFERRED(vulkan);
FN_XAKU_CMD_DESTROY_TEXTURE_VIEW_DEFERRED(vulkan);
FN_XAKU_CMD_DESTROY_SAMPLER_DEFERRED(vulkan);
FN_XAKU_CMD_DESTROY_TLAS_DEFERRED(vulkan);
FN_XAKU_CMD_DESTROY_BLAS_DEFERRED(vulkan);
FN_XAKU_CMD_PUSH_CONSTANT(vulkan);
FN_XAKU_CMD_SET_COMPUTE_PIPELINE(vulkan);
FN_XAKU_CMD_SET_RASTER_PIPELINE(vulkan);
FN_XAKU_CMD_SET_RAY_TRACING_PIPELINE(vulkan);
FN_XAKU_CMD_SET_VIEWPORT(vulkan);
FN_XAKU_CMD_SET_SCISSOR(vulkan);
FN_XAKU_CMD_SET_DEPTH_BIAS(vulkan);
FN_XAKU_CMD_SET_INDEX_BUFFER(vulkan);
FN_XAKU_CMD_BEGIN_RENDERING(vulkan);
FN_XAKU_CMD_END_RENDERING(vulkan);
FN_XAKU_CMD_DISPATCH(vulkan);
FN_XAKU_CMD_DISPATCH_INDIRECT(vulkan);
FN_XAKU_CMD_DRAW(vulkan);
FN_XAKU_CMD_DRAW_INDEXED(vulkan);
FN_XAKU_CMD_DRAW_INDIRECT(vulkan);
FN_XAKU_CMD_DRAW_INDIRECT_COUNT(vulkan);
FN_XAKU_CMD_MESH_TASKS(vulkan);
FN_XAKU_CMD_MESH_TASKS_INDIRECT(vulkan);
FN_XAKU_CMD_MESH_TASKS_INDIRECT_COUNT(vulkan);
FN_XAKU_CMD_TRACE_RAYS(vulkan);
FN_XAKU_CMD_TRACE_RAYS_INDIRECT(vulkan);
FN_XAKU_CMD_WRITE_TIMESTAMPS(vulkan);
FN_XAKU_CMD_RESET_TIMESTAMPS(vulkan);
FN_XAKU_CMD_BEGIN_LABEL(vulkan);
FN_XAKU_CMD_END_LABEL(vulkan);
FN_XAKU_COMPILE_COMMAND_LIST(vulkan);

#endif /* XAKU_VULKAN */
