#include "vk_xaku.h"
#ifdef XAKU_VULKAN

FN_XAKU_MEMORY_BUFFER_REQUIREMENTS(vulkan);
FN_XAKU_MEMORY_TEXTURE_REQUIREMENTS(vulkan);
FN_XAKU_MEMORY_ASSEMBLY(vulkan);
FN_XAKU_MEMORY_DISASSEMBLY(vulkan);

#endif /* XAKU_VULKAN */
