#include "vk_xaku.h"
#ifdef XAKU_VULKAN

FN_XAKU_COMPUTE_PIPELINE_ASSEMBLY(vulkan);
FN_XAKU_COMPUTE_PIPELINE_DISASSEMBLY(vulkan);
FN_XAKU_RASTER_PIPELINE_ASSEMBLY(vulkan);
FN_XAKU_RASTER_PIPELINE_DISASSEMBLY(vulkan);
FN_XAKU_RAY_TRACING_PIPELINE_ASSEMBLY(vulkan);
FN_XAKU_RAY_TRACING_PIPELINE_DISASSEMBLY(vulkan);

#endif /* XAKU_VULKAN */
