#ifndef LAKE_INLINE_TYPEDEFS
#error "A macro LAKE_INLINE_TYPEDEFS must be defined before including this file."
#endif

#include "../types.h"
#include "../endian.h"
#include "../atomic.h"
#include "../simd.h"

LAKE_INLINE_TYPEDEFS(s8)
LAKE_INLINE_TYPEDEFS(s16)
LAKE_INLINE_TYPEDEFS(s32)
LAKE_INLINE_TYPEDEFS(s64)

LAKE_INLINE_TYPEDEFS(u8)
LAKE_INLINE_TYPEDEFS(u16)
LAKE_INLINE_TYPEDEFS(u32)
LAKE_INLINE_TYPEDEFS(u64)

LAKE_INLINE_TYPEDEFS(sptr)
LAKE_INLINE_TYPEDEFS(uptr)
LAKE_INLINE_TYPEDEFS(ssize)
LAKE_INLINE_TYPEDEFS(usize)

LAKE_INLINE_TYPEDEFS(f32)
LAKE_INLINE_TYPEDEFS(f64)

LAKE_INLINE_TYPEDEFS(le16)
LAKE_INLINE_TYPEDEFS(le32)
LAKE_INLINE_TYPEDEFS(le64)

LAKE_INLINE_TYPEDEFS(be16)
LAKE_INLINE_TYPEDEFS(be32)
LAKE_INLINE_TYPEDEFS(be64)

LAKE_INLINE_TYPEDEFS(atomic_s8)
LAKE_INLINE_TYPEDEFS(atomic_s16)
LAKE_INLINE_TYPEDEFS(atomic_s32)
LAKE_INLINE_TYPEDEFS(atomic_s64)

LAKE_INLINE_TYPEDEFS(atomic_u8)
LAKE_INLINE_TYPEDEFS(atomic_u16)
LAKE_INLINE_TYPEDEFS(atomic_u32)
LAKE_INLINE_TYPEDEFS(atomic_u64)

LAKE_INLINE_TYPEDEFS(atomic_sptr)
LAKE_INLINE_TYPEDEFS(atomic_uptr)
LAKE_INLINE_TYPEDEFS(atomic_ssize)
LAKE_INLINE_TYPEDEFS(atomic_usize)

LAKE_INLINE_TYPEDEFS(svec2)
LAKE_INLINE_TYPEDEFS(svec3)
LAKE_INLINE_TYPEDEFS(svec4)

LAKE_INLINE_TYPEDEFS(vec2)
LAKE_INLINE_TYPEDEFS(vec3)
LAKE_INLINE_TYPEDEFS(vec4)

LAKE_INLINE_TYPEDEFS(quat)

LAKE_INLINE_TYPEDEFS(mat2)
LAKE_INLINE_TYPEDEFS(mat2x3)
LAKE_INLINE_TYPEDEFS(mat2x4)

LAKE_INLINE_TYPEDEFS(mat3)
LAKE_INLINE_TYPEDEFS(mat3x2)
LAKE_INLINE_TYPEDEFS(mat3x4)

LAKE_INLINE_TYPEDEFS(mat4)
LAKE_INLINE_TYPEDEFS(mat4x2)
LAKE_INLINE_TYPEDEFS(mat4x3)

#undef LAKE_INLINE_TYPEDEFS
